### ISSUE TITLE
Generator crashes on Node 8

### ISSUE THREAD

**Issue by sbaechler** [liferay/generator-liferay-theme#31]
When I run the generator with Node 8 it crashes with the following message:

```
Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-liferay-theme/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:32:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

Node 8 is the current LTS version. The generator is working with Node 6.

There are a few security notices as well:

```
WARN notice [SECURITY] mime has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=mime&version=1.3.6 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN notice [SECURITY] is-my-json-valid has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=is-my-json-valid&version=2.16.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN notice [SECURITY] lodash has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=3.6.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
```

**Comment by jbalsas** [comment]
Hey @sbaechler, would you mind filing this in the new [liferay-themes-sdk repo](https://github.com/liferay/liferay-themes-sdk/issues/new)?

Also, could you please indicate which version of the generator are you using?

Thanks!

**Comment by sbaechler** [comment]
Done
https://github.com/liferay/liferay-themes-sdk/issues/43
